name: beatiful_planets_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive: 0.13.2
  slide_action: ^0.0.1+3
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  dio: ^5.4.3+1
  simple_gradient_text: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/first_integration.riv
    - assets/images/Forward.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
